CHANGES.rst, MANIFEST.in, RELEASE-NOTES.rst, invenio_access/version.py
=> Invenio-Access v0.1.0

invenio_access/scripts/webaccessadmin.py
=> global: removal of unused imports

invenio_access/admin.py, invenio_access/bases.py, invenio_access/control.py, invenio_access/engine.py, invenio_access/firerole.py, invenio_access/local_config.py, invenio_access/mailcookie.py, invenio_access/models.py, invenio_access/scripts/webaccessadmin.py, invenio_access/upgrades/access_2015_05_06_accROLE_accACTION_accARGUMENT_id.py, invenio_access/views/admin.py, requirements-devel.txt, setup.py, tests/test_firerole.py
* FIX Adds missing invenio_ext dependency and fixes its imports.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> installation: fix invenio_ext imports

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
=> Invenio-Access v0.2.0

invenio_access/control.py, invenio_access/local_config.py
Signed-off-by: Sebastian Witowski <witowski.sebastian@gmail.com>
=> global: fix for invenio.config import

invenio_access/models.py
Transforms lambdas into functions and moves the import in them.
=> global: fix models app context

.gitignore, .travis.yml, examples/app.py, invenio_access/cli.py, invenio_access/models.py, invenio_access/permissions.py, tests/conftest.py, tests/test_invenio_access_cli.py, tests/test_invenio_access_permissions.py
* Adds possibility to deny user or role from performing an action. (addresses #25)
=> permissions: allow/deny actions

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py, setup.py
=> Invenio-Access v1.0.0a1

invenio_access/version.py
=> installation: post release version bump

.travis.yml
=> travis: compile_catalog removal from deploy

.travis.yml, INSTALL.rst, docs/api.rst, invenio_access/__init__.py, invenio_access/cli.py, invenio_access/ext.py, invenio_access/models.py, invenio_access/permissions.py, setup.py, tests/conftest.py, tests/test_invenio_access.py, tests/test_invenio_access_cli.py, tests/test_invenio_access_permissions.py
=> docs: detailed usage

.travis.yml, invenio_access/__init__.py, invenio_access/ext.py, invenio_access/models.py, invenio_access/permissions.py, invenio_access/proxies.py, setup.py, tests/test_invenio_access_permissions.py, tests/test_invenio_access_permissions_cache.py
=> global: refactoring of cache and DynamicPermission

setup.py
* Adds the entry point for this extension in invenio_base.apps.
(closes #40)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> setup: fix entry point groups for extension

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
(closes #38)
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>
=> release: v1.0.0a2

invenio_access/version.py
=> version: post-release bump

.travis.yml, examples/app.py, setup.py
=> global: flask-security 1.7.5 fix

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
=> release: v1.0.0a3

examples/adminapp.py, examples/app.py, invenio_access/admin.py, invenio_access/models.py, setup.py, tests/test_admin.py, tests/test_invenio_access.py, tests/test_invenio_access_cli.py, tests/test_invenio_access_permissions.py
=> global: admin view for managing access to actions

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
=> release: v1.0.0a4

AUTHORS.rst, docs/conf.py, invenio_access/permissions.py, run-tests.sh, setup.py, tests/test_invenio_access_permissions.py
* Adds 'superuser-access' which grants access to all DynamicPermissions.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> permissions: addition of SuperUser

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> release: v1.0.0a6

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py, setup.py
* Registers the 'superuser-access' action through an entrypoint.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>
=> installation: superuser_access entrypoint

examples/app.py
* Unifies arguments in accounts cli.
(addresses inveniosoftware/invenio-accounts#90)
--
This is a last update to Accounts cli unification and it closes inveniosoftware/invenio-accounts#90 .
=> examples: accounts cli unification

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> release: v1.0.0a8

docs/api.rst, invenio_access/config.py, invenio_access/ext.py, invenio_access/version.py, setup.py
* Adds new configuration option `ACCESS_CACHE`.  (closes #66)
=> config: access cache object

docs/api.rst
=> docs: removal of :undoc-members:

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
=> release: v1.0.0a9

examples/app.py, invenio_access/__init__.py
* BETTER Adds section in the documentation on how to discover
existing actions.
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
=> docs: discovering actions

.travis.yml, .tx/config, examples/adminapp.py, examples/app.py, invenio_access/__init__.py, invenio_access/cli.py, setup.py, tests/conftest.py, tests/test_invenio_access.py
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
=> i18n: tx configuration fix

examples/adminapp.py, examples/app.py, invenio_access/__init__.py, invenio_access/cli.py, setup.py, tests/conftest.py, tests/test_invenio_access.py
=> installation: Flask>=0.11

invenio_access/ext.py, invenio_access/models.py, invenio_access/permissions.py
* Improves documentation. (addresses #72)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> docs: addition of param and result sections

.gitignore, MANIFEST.in, examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/templates/invenio_access/base.html, examples/templates/invenio_access/limited.html, examples/templates/invenio_access/open.html, tests/test_examples_app.py
* Adds test_example_app.py. (closes #84)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: addition of test_example_app.py

MANIFEST.in, docs/conf.py, docs/requirements.txt
=> docs: addition of readthedocs.yml

examples/app.py, run-tests.sh
Signed-off-by: Krzysztof Nowak <k.nowak@cern.ch>
=> setup: isort glob fix

setup.py
Signed-off-by: Krzysztof Nowak k.nowak@cern.ch
=> installation: invenio-accounts version bump

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py, setup.py
Signed-off-by: Krzysztof Nowak k.nowak@cern.ch
=> release: v1.0.0.a10

invenio_access/alembic/2f63be7b7572_create_access_tables.py, invenio_access/alembic/67ba0de65fbb_create_access_branch.py, setup.py, tests/conftest.py, tests/test_invenio_access.py
=> global: initial alembic recipes

CHANGES.rst, RELEASE-NOTES.rst, examples/app-teardown.sh, examples/app.py, invenio_access/ext.py, invenio_access/version.py, setup.py
Needed to unblock https://github.com/inveniosoftware/invenio-files-rest/pull/133
=> release: v1.0.0a11

examples/app-fixtures.sh, invenio_access/cli.py, invenio_access/models.py, invenio_access/version.py, tests/test_invenio_access_cli.py
=> cli: allow any / deny all

invenio_access/alembic/2f63be7b7572_create_access_tables.py, invenio_access/models.py
=> models: forced name of Boolean column

.editorconfig, .gitignore, .travis.yml, CONTRIBUTING.rst, MANIFEST.in, docs/Makefile, docs/conf.py, docs/examplesapp.rst, docs/make.bat, setup.cfg, setup.py, tests/test_examples_app.py
* FIX Adds changes according to release preparation checklist.
Signed-off-by: Paulina Lach <paulina.malgorzata.lach@cern.ch>
=> global: release checklist

.lgtm, .travis.yml, .tx/config, AUTHORS.rst, CONTRIBUTING.rst, INSTALL.rst, MANIFEST.in, README.rst, RELEASE-NOTES.rst, docs/api.rst, docs/conf.py, docs/configuration.rst, docs/usage.rst, examples/app-fixtures.sh, examples/app.py, invenio_access/__init__.py, invenio_access/cli.py, invenio_access/models.py, invenio_access/permissions.py, pytest.ini, run-tests.sh, setup.py
* Fixes minor discrepancies as described in the Release
preparation checklist.
* Improves the documentation. (closes #114)
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> global: standardize the module before the beta

invenio_access/alembic/04480be1593e_add_actionsystemroles.py, invenio_access/models.py, invenio_access/permissions.py, pytest.ini, run-tests.sh, tests/test_invenio_access_permissions.py, tests/test_invenio_access_permissions_cache.py
* Fix pytest config
* Adds ActionSystemRoles model
* Adds a new Permission which denies access by default.
This PR doesn't have the identity loader.
=> Refactor permission

CHANGES.rst, RELEASE-NOTES.rst, invenio_access/version.py
Signed-off-by: Nicolas Harraudeau <nicolas.harraudeau@cern.ch>
=> release: v1.0.0b1

invenio_access/admin.py
=> Changed label from exclude to deny and form inputs order.

invenio_access/permissions.py, invenio_access/version.py
* Changes DynamicPermissions pending deprecation warning to a full
deprecation warning.
=> permissions: change silent to loud warning

invenio_access/__init__.py
Rearrange imports
(Closes #159)
=> isort: rearrange imports

docs/api.rst, examples/app.py, invenio_access/__init__.py, invenio_access/permissions.py, tests/conftest.py, tests/test_invenio_access_cli.py, tests/test_invenio_access_permissions.py, tests/test_invenio_access_permissions_cache.py
=> permission: remove DynamicPermission

CHANGES.rst, invenio_access/version.py
=> release: v1.2.0

.travis.yml, CHANGES.rst, invenio_access/__init__.py, invenio_access/version.py, requirements-devel.txt, setup.py, tests/test_permissions_cache.py
* clean and update travis.yml
* replace werkzeug.contrib cache with cachelib
* closes #170
=> global: update python dependencies

docs/conf.py, invenio_access/__init__.py, invenio_access/cli.py, invenio_access/ext.py, invenio_access/factory.py, invenio_access/models.py, invenio_access/proxies.py, invenio_access/utils.py, invenio_access/version.py, run-tests.sh, setup.py, tests/conftest.py, tests/test_admin.py, tests/test_cli.py, tests/test_invenio_access.py, tests/test_permissions_cache.py
* Pushes a Flask app context during building of documentation in order
to be able to include the proxies to the current application.
* Removes __future__ and unused imports.
=> tests: fix ci build

.tx/config, babel.ini, invenio_access/translations/messages.pot
*  remove jinja extensions
* update .pot
related inveniosoftware/invenio-app-rdm/issues/1664
=> i18n: update translations file

invenio_access/translations/de/LC_MESSAGES/messages.po
* add german translations
related inveniosoftware/invenio-app-rdm/issues/1664
=> i18n: adds german translations

invenio_access/permissions.py
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/240
=> permissions:  add system access permisssion

CHANGES.rst, invenio_access/__init__.py, setup.cfg
- setup: bump major dependencies
- release: v4.0.0
=> bump major
